-- Generated from generator/demo_specs/aws-vietnam-electronics-quality.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-vietnam-electronics-quality
-- This is the schema that is actually deployed for VIETNAM_ELECTRONICS_QUALITY.

-- Alerts fire on the bottom tail of Quality Escapes
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_QUALITY_ESCAPES) AS T
  FROM RAW.INSPECTIONS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_QUALITY_ESCAPES <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_QUALITY_ESCAPES), 2) AS AVG_QUALITY_ESCAPES,
  ROUND(AVG(f.KPI_FIRST_PASS_YIELD), 2) AS AVG_FIRST_PASS_YIELD,
  ROUND(AVG(f.KPI_CUSTOMER_RETURNS), 2) AS AVG_CUSTOMER_RETURNS,
  ROUND(AVG(f.KPI_REWORK_RATE), 2) AS AVG_REWORK_RATE,
  ROUND(AVG(f.KPI_AOI_DETECTION), 2) AS AVG_AOI_DETECTION
FROM RAW.INSPECTIONS f
JOIN RAW.PRODUCTS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_QUALITY_ESCAPES), 2) AS AVG_QUALITY_ESCAPES,
  ROUND(AVG(f.KPI_FIRST_PASS_YIELD), 2) AS AVG_FIRST_PASS_YIELD,
  ROUND(AVG(f.KPI_CUSTOMER_RETURNS), 2) AS AVG_CUSTOMER_RETURNS,
  ROUND(AVG(f.KPI_REWORK_RATE), 2) AS AVG_REWORK_RATE,
  ROUND(AVG(f.KPI_AOI_DETECTION), 2) AS AVG_AOI_DETECTION
FROM RAW.INSPECTIONS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_FIRST_PASS_YIELD) AS KPI_FIRST_PASS_YIELD, AVG(KPI_CUSTOMER_RETURNS) AS KPI_CUSTOMER_RETURNS, AVG(KPI_QUALITY_ESCAPES) AS KPI_QUALITY_ESCAPES, AVG(KPI_REWORK_RATE) AS KPI_REWORK_RATE, AVG(KPI_AOI_DETECTION) AS KPI_AOI_DETECTION FROM RAW.INSPECTIONS),
     en AS (SELECT SUM(KPI_INSPECTIONS_MTD) AS KPI_INSPECTIONS_MTD, SUM(KPI_DPMO) AS KPI_DPMO FROM RAW.PRODUCTS)
  SELECT 1 AS SORT_ORDER, 'First Pass Yield' AS TITLE, KPI_FIRST_PASS_YIELD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FIRST_PASS_YIELD), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Customer Returns' AS TITLE, KPI_CUSTOMER_RETURNS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CUSTOMER_RETURNS), 2) AS DECIMAL(38,2))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Quality Escapes' AS TITLE, KPI_QUALITY_ESCAPES AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_QUALITY_ESCAPES)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Inspections (MTD)' AS TITLE, KPI_INSPECTIONS_MTD AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_INSPECTIONS_MTD) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'DPMO' AS TITLE, KPI_DPMO AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_DPMO)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Rework Rate' AS TITLE, KPI_REWORK_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_REWORK_RATE), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'AOI Detection' AS TITLE, KPI_AOI_DETECTION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_AOI_DETECTION), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
